In [35]:
import numpy as np

import math 

p1 = np.array([1,2])
p2 = np.array([3,4])
def distance(p1, p2):
    """
    >>> distance(np.array([0,0]), np.array([1,1]))
    1.4142135623730951
    
    >>> distance(np.array([1,2]), np.array([3,4]))
    2.8284271247461903
    
    >>> distance(np.array([5,2]), np.array([-2,-1]))
    7.615773105863909
    """    
    h = []
    for c in range(len(p1)):
        p = p2-p1
        h.append( math.pow(p[c],2))
        a = np.array(h)
    
        distance = math.sqrt(np.sum(a))
    return distance


In [36]:
distance(p1,p2)

2.8284271247461903

In [45]:
p1 = np.array([1,2])
p2 = np.array([1,1])
points = np.array([[3,-1], [2,1], [5, 2], [10, 1], [-2, -5]])

def n_distances(p1, points):
    """
    >>> n_distances(np.array([0,0]), np.array([[1,1]]))
    array([1.41421356])
    
    >>> n_distances(np.array([0,0]), np.array([[1,1], [2,2]]))
    array([1.41421356, 2.82842712])
    
    >>> n_distances(np.array([1,2]), np.array([[3,-1], [2,1], [5, 2], [10, 1], [-2, -5]]))
    array([3.60555128, 1.41421356, 4.        , 9.05538514, 7.61577311])
    """
    
    x = points[0:] - p1
    y = points[0:] - p1
    z = x * y
    a = np.sum(z,axis = 1 )

    n = []
    for c in range(len(a)):
        n.append(math.sqrt(a[c]))
    n_distance = np.array(n)
    return n_distance

In [46]:
n_distances(p2, points)

array([2.82842712, 1.        , 4.12310563, 9.        , 6.70820393])