pandas é uma biblioteca q possibilita a criação e manipulação de dataframe,que são arrays multidimensionais
com rotulos nas linhas e nas colunas uma estrutura semelhante a uma tabela.


"MULTIDIMENSIONAIS"
-É UMA FORMA REPRESENTATIVA DO CRUZAMENTO DE INFORMAÇÕES

COSTUMA SER IMPORTADO DA SEGUINTE FORMA O PANDAS

In [5]:
import pandas as pd

SERIES

a classe series implementa um array uni dimensional

In [6]:
import pandas as pd
data = pd.Series([1.5, 2.5, 3.5, 4.5, 5.5])
data

0    1.5
1    2.5
2    3.5
3    4.5
4    5.5
dtype: float64

acessando os valores e indices de uma Series

In [7]:
data.index

RangeIndex(start=0, stop=5, step=1)

In [8]:
data.values

array([1.5, 2.5, 3.5, 4.5, 5.5])

In [9]:
data[0]

1.5

In [10]:
data[2:5]

2    3.5
3    4.5
4    5.5
dtype: float64

uma series pode ter indices que não são números

In [11]:
data = pd.Series([1,2,3,4,5],index = ["a","b","c","d","e"])
data

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [12]:
data["a"]

1

In [13]:
data["a":"d"]

a    1
b    2
c    3
d    4
dtype: int64

podemos criar Series apartir de dicionarios

In [14]:
population_dict = {"joão pessoa":235456,
             "recife":32567,
             "guarulhos":56378768,
             "são paulo":325546464,
             "alagoas":876576}

In [15]:
population = pd.Series(population_dict)
population

joão pessoa       235456
recife             32567
guarulhos       56378768
são paulo      325546464
alagoas           876576
dtype: int64

DATA frama

a clase data frama é uma estrutura semelhante a uma tabela,
podemos entender como uma sequencia de Series que compartilham
um mesmo indice

In [16]:
area_dict = {"joão pessoa":5354653,
             "recife":656577,
             "guarulhos":67513412,
             "são paulo":245345434,
             "alagoas":98724524}

area = pd.Series(area_dict)
area

joão pessoa      5354653
recife            656577
guarulhos       67513412
são paulo      245345434
alagoas         98724524
dtype: int64

"podemos notar q population_dict e area_dict possuem as mesmas chaves"

In [17]:
states = pd.DataFrame({"population": population,"area": area})
states

population       area
joão pessoa      235456    5354653
recife            32567     656577
guarulhos      56378768   67513412
são paulo     325546464  245345434
alagoas          876576   98724524

os data frames possuem valores,indices e colunas

In [18]:
states.values

array([[   235456,   5354653],
       [    32567,    656577],
       [ 56378768,  67513412],
       [325546464, 245345434],
       [   876576,  98724524]], dtype=int64)

In [19]:
states.index

Index(['joão pessoa', 'recife', 'guarulhos', 'são paulo', 'alagoas'], dtype='object')

In [20]:
states.columns

Index(['population', 'area'], dtype='object')

os dataframes mapeiam as colunas para uma series,assim,através do nome "columns",assim nos acessamos suas series correspondentes

In [21]:
states["area"]

joão pessoa      5354653
recife            656577
guarulhos       67513412
são paulo      245345434
alagoas         98724524
Name: area, dtype: int64

podemos construir um data frame apartir de uma array bidimensional,o array corresponde aos valores

In [22]:
import numpy as np
data = np.random.random((3,3))
pd.DataFrame(data)


0         1         2
0  0.199528  0.873127  0.836204
1  0.397857  0.589600  0.125504
2  0.663428  0.560580  0.022374

In [23]:
data

array([[0.19952775, 0.87312743, 0.83620404],
       [0.39785706, 0.58959965, 0.12550416],
       [0.66342751, 0.56058044, 0.02237434]])

para definir os indeces e colunas usamos:

In [24]:
pd.DataFrame(data,columns = ["a","b","c"],index =["x","y","z"] )

a         b         c
x  0.199528  0.873127  0.836204
y  0.397857  0.589600  0.125504
z  0.663428  0.560580  0.022374

INDEXAÇÃO

In [25]:
data = pd.Series ([1,2,3,4,5],
                 [2,4,6,8,10])

In [26]:
data

2     1
4     2
6     3
8     4
10    5
dtype: int64

In [27]:
data[1:4]

4    2
6    3
8    4
dtype: int64

para não ter ambiguidade, o pandas fornece dois atributos para diferenciar o numero da linha do valor do indice ".loc",referenciando o indece
real e o ".iloc" referenciando ao indice linha

In [28]:
data.loc[2]

1

In [29]:
data.loc[4]

2

In [30]:
data.iloc[1]

2

In [31]:
data.iloc[4]

5

In [32]:
data.loc[2:4]

2    1
4    2
dtype: int64

ACESSANDO COLUNAS NO DATA FRAME

In [33]:
states ["area"]

joão pessoa      5354653
recife            656577
guarulhos       67513412
são paulo      245345434
alagoas         98724524
Name: area, dtype: int64

In [34]:
states["population"]

joão pessoa       235456
recife             32567
guarulhos       56378768
são paulo      325546464
alagoas           876576
Name: population, dtype: int64

para modificar colunas utilizamos operadores de atribuição

In [35]:
states ["area"] = pd.Series({"joão pessoa":211.5,
                            "recife":218.3,
                            "guarulhos":319.2,
                            "são paulo":152.300,
                            "alagoas":27.768})

states

ou criar uma coluna nova

In [37]:
states["density"] = states["population"] / states["area"]

In [38]:
states

population     area       density
joão pessoa      235456  211.500  1.113267e+03
recife            32567  218.300  1.491846e+02
guarulhos      56378768  319.200  1.766252e+05
são paulo     325546464  152.300  2.137534e+06
alagoas          876576   27.768  3.156785e+04

para eu inverter as linhas e colunas basta eu:

In [40]:
states.T

joão pessoa        recife     guarulhos     são paulo  \
population  235456.000000  32567.000000  5.637877e+07  3.255465e+08   
area           211.500000    218.300000  3.192000e+02  1.523000e+02   
density       1113.267139    149.184608  1.766252e+05  2.137534e+06   

                  alagoas  
population  876576.000000  
area            27.768000  
density      31567.847882

"MANO NÃO ESQUECE TODAS AS LETRAR INICIAIS DOS MODULOS SÃO EM MAIUSCULAS!"

os atributos ".loc" e "i.loc",tambem funcionam com os Data Frame.

In [42]:
states.loc["joão pessoa"]

population    235456.000000
area             211.500000
density         1113.267139
Name: joão pessoa, dtype: float64

podemos uasr alguns padrões de acesso exisistentes no numpy

In [44]:
states.loc[["joão pessoa","alagoas"]]

population     area       density
joão pessoa      235456  211.500   1113.267139
alagoas          876576   27.768  31567.847882

In [46]:
states.loc[states.density > 100,["population","density"]]

population       density
joão pessoa      235456  1.113267e+03
recife            32567  1.491846e+02
guarulhos      56378768  1.766252e+05
são paulo     325546464  2.137534e+06
alagoas          876576  3.156785e+04

In [47]:
states.loc[states.density > 100,["population"]]

population
joão pessoa      235456
recife            32567
guarulhos      56378768
são paulo     325546464
alagoas          876576

ENTRADA E SAIDA

os pandas taz a função ".read_csv()" que carrega arquivos csv e os transforma em um DataFrama

In [49]:
movies_df = pd.read_csv ("movies.csv")

In [50]:
movies_df

Title    US Gross  Worldwide Gross  US DVD Sales  \
0                 The Land Girls    146083.0         146083.0           NaN   
1         First Love, Last Rites     10876.0          10876.0           NaN   
2     I Married a Strange Person    203134.0         203134.0           NaN   
3           Let's Talk About Sex    373615.0         373615.0           NaN   
4                           Slam   1009819.0        1087521.0           NaN   
...                          ...         ...              ...           ...   
3196  Zack and Miri Make a Porno  31452765.0       36851125.0    21240321.0   
3197                      Zodiac  33080084.0       83080084.0    20983030.0   
3198                        Zoom  11989328.0       12506188.0     6679409.0   
3199         The Legend of Zorro  45575336.0      141475336.0           NaN   
3200           The Mask of Zorro  93828745.0      233700000.0           NaN   

      Production Budget Release Date MPAA Rating  Running Time (min)  \
0             8000000.0    12-Jun-98           R                 NaN   
1              300000.0     7-Aug-98           R                 NaN   
2              250000.0    28-Aug-98         NaN                 NaN   
3              300000.0    11-Sep-98         NaN                 NaN   
4             1000000.0     9-Oct-98           R                 NaN   
...                 ...          ...         ...                 ...   
3196         24000000.0    31-Oct-08           R               101.0   
3197         85000000.0     2-Mar-07           R               157.0   
3198         35000000.0    11-Aug-06          PG                 NaN   
3199         80000000.0    28-Oct-05          PG               129.0   
3200         65000000.0    17-Jul-98       PG-13               136.0   

             Distributor                        Source        Major Genre  \
0               Gramercy                           NaN                NaN   
1                 Strand                           NaN              Drama   
2              Lionsgate                           NaN             Comedy   
3              Fine Line                           NaN             Comedy   
4                Trimark           Original Screenplay              Drama   
...                  ...                           ...                ...   
3196       Weinstein Co.           Original Screenplay             Comedy   
3197  Paramount Pictures     Based on Book/Short Story  Thriller/Suspense   
3198       Sony Pictures  Based on Comic/Graphic Novel          Adventure   
3199       Sony Pictures                        Remake          Adventure   
3200       Sony Pictures                        Remake          Adventure   

             Creative Type         Director  Rotten Tomatoes Rating  \
0                      NaN              NaN                     NaN   
1                      NaN              NaN                     NaN   
2                      NaN              NaN                     NaN   
3                      NaN              NaN                    13.0   
4     Contemporary Fiction              NaN                    62.0   
...                    ...              ...                     ...   
3196  Contemporary Fiction      Kevin Smith                    65.0   
3197         Dramatization    David Fincher                    89.0   
3198            Super Hero     Peter Hewitt                     3.0   
3199    Historical Fiction  Martin Campbell                    26.0   
3200    Historical Fiction  Martin Campbell                    82.0   

      IMDB Rating  IMDB Votes  
0             6.1      1071.0  
1             6.9       207.0  
2             6.8       865.0  
3             NaN         NaN  
4             3.4       165.0  
...           ...         ...  
3196          7.0     55687.0  
3197          NaN         NaN  
3198          3.4      7424.0  
3199          5.7     21161.0  
3200          6.7      4789.0  

[3201 rows x 16 columns]

NameError: name 'DataSets' is not defined